version: '3.5'
services:
  web:
    build: .
    ports:
      - 80:80
    env_file:
      - .dev.env
    volumes:
      # - ./conf/usac_org.conf:/etc/httpd/conf.d/usac_org.conf
      # - ./sql:/sql
      - ./site:/var/www/usacycling_org/site
      - ./craft:/var/www/usacycling_org/craft
      - type: volume
        source: nodemodules
        target: /var/www/usacycling_org/site/node_modules
        volume:
          nocopy: true
    depends_on:
      - mysql
    links:
      - mysql
  buildchain:
    build:
      context: ./site
      dockerfile: ./Dockerfile
    volumes:
      - ./site:/project
      - type: volume
        source: nodemodules
        target: /project/node_modules
        volume:
          nocopy: true
      - type: volume
        source: npm
        target: /root/.npm
        volume:
          nocopy: true
  mysql:
    image: mysql:5.6
    env_file:
      - .dev.env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      # - ./sql:/docker-entrypoint-initdb.d
volumes:
  mysql:
  npm:
  nodemodules:
